name: Metrics
on:
  # ğŸŒ Payawal 24kata sarayak update wenna
  schedule: [{cron: "0 0 * * *"}]
  # âœŒï¸ Manual run karanna puluwan wenna
  workflow_dispatch:
  # ğŸ’¡ Main branch eka update unama run wenna
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: pathumkashmira
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          
          # ğŸ§© Plugins (Sure ekatama wada karana tika)
          
          # 1. Isometric Calendar (Ara 3D kotu tika - Meka wada!)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # 2. Languages (Bhasha tika)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 8
          
          # 3. Lines of Code
          plugin_lines: yes
          
          # 4. Traffic
          plugin_traffic: yes
          
          # âŒ Error ena nisa meka danata disable kala
          # plugin_habits: yes
          # plugin_habits_facts: yes
          # plugin_habits_charts: yes
          # plugin_achievements: yes
          # plugin_achievements_display: compact
