name: Metrics
on:
  # ðŸŒ Payawal 24kata sarayak update wenna
  schedule: [{cron: "0 0 * * *"}]
  # âœŒï¸ Manual run karanna puluwan wenna
  workflow_dispatch:
  # ðŸ’¡ Main branch eka update unama run wenna
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token eka methana link wenawa
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: pathumkashmira
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          
          # ðŸ§© Plugins (Lassana Graphics Tika)
          
          # 1. Isometric Calendar (Ara 3D kotu tika)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # 2. Languages (Pawiichi karana bhasha)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          
          # 3. Habits (Coding karana welawal)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # 4. Achievements (Labuna Trophies)
          plugin_achievements: yes
          plugin_achievements_display: compact
          
          # 5. Lines of Code (Kochchara code liyala thiyenawada)
          plugin_lines: yes
          
          # 6. Traffic (Kochchara kattiya enawada)
          plugin_traffic: yes
